# Generated by Django 4.2.5 on 2023-09-29 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitudes_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('fecha_solicitado', models.DateTimeField(editable=False)),
                ('fecha_recibido', models.DateTimeField(editable=False)),
                ('fecha_proceso', models.DateTimeField(editable=False)),
                ('fecha_terminado', models.DateTimeField(editable=False)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expedientes_app.estadoexpediente')),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='solicitudes_app.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='ProcesoExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encargado', models.TextField()),
                ('organo_universitario', models.TextField()),
                ('titulo', models.TextField(max_length=100)),
                ('descripcion', models.TextField(max_length=250)),
                ('usuario', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='expedientes_app.expediente')),
            ],
        ),
    ]
