# Generated by Django 4.2.5 on 2023-09-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='fecha_proceso',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='fecha_recibido',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='fecha_solicitado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='fecha_terminado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
