# Generated by Django 4.2.5 on 2023-10-27 05:06

from django.db import migrations, models
import django.db.models.deletion
import solicitudes_app.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sedes_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_expediente', models.CharField(editable=False, max_length=20, unique=True)),
                ('rol', models.CharField(max_length=30, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=8)),
                ('cui', models.CharField(max_length=8, null=True)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=30)),
                ('tipo_solicitud', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=250)),
                ('organo_universitario', models.CharField(max_length=80, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sedes_app.sede')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoSolicitud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreArchivo', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to=solicitudes_app.models.archivo_ruta)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes_app.solicitud')),
            ],
        ),
    ]
