# Generated by Django 4.2.5 on 2023-10-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='encargado',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='organo_universitario',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='otro_rol',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='prueba_1',
            field=models.FileField(null=True, upload_to='files/file_1/'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='prueba_2',
            field=models.FileField(null=True, upload_to='files/file_2/'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='prueba_3',
            field=models.FileField(null=True, upload_to='files/file_3/'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='prueba_4',
            field=models.FileField(null=True, upload_to='files/file_4/'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='prueba_5',
            field=models.FileField(null=True, upload_to='files/file_5/'),
        ),
    ]
