# Generated by Django 4.2.5 on 2023-10-27 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes_app', '0002_alter_solicitud_codigo_expediente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivosolicitud',
            old_name='nombreArchivo',
            new_name='nombre',
        ),
    ]
