# Generated by Django 4.2.5 on 2023-10-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes_app', '0004_alter_archivosolicitud_solicitud'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArchivoSolicitud',
            new_name='Archivo',
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='codigo_expediente',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='cui',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
