# Generated by Django 4.2.5 on 2023-10-30 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes_app', '0005_rename_archivosolicitud_archivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='nombre',
        ),
    ]
