# Generated by Django 4.2.5 on 2024-01-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes_app', '0010_solicitud_encargado_solicitud_estado_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='expone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='solicita',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
    ]
