# Generated by Django 4.2.5 on 2024-02-07 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes_app', '0011_solicitud_expone_solicitud_solicita_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='descripcion',
        ),
    ]
