# Generated by Django 4.2.5 on 2024-02-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes_app', '0012_remove_solicitud_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='expone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='solicita',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
