# Generated by Django 4.2.5 on 2023-10-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('estudiante', 'Estudiante'), ('docente', 'Docente'), ('administrativo', 'Administrativo'), ('otro', 'Otro')], max_length=20)),
                ('otro_rol', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=10)),
                ('cui', models.CharField(max_length=10)),
                ('area_sede', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(max_length=200)),
                ('numero_telefonico', models.CharField(max_length=20)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('tipo_solicitud', models.CharField(choices=[('queja', 'Queja'), ('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia'), ('consulta', 'Consulta')], max_length=20)),
                ('sustentacion_solicitud', models.TextField()),
                ('autoriza_notificacion', models.BooleanField(default=False)),
                ('archivos_adjuntos', models.FileField(blank=True, null=True, upload_to='adjuntos/')),
            ],
        ),
    ]
