# Generated by Django 4.2.5 on 2024-01-21 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes_app', '0008_estadosolicitud_solicitud_encargado_and_more'),
        ('procesos_app', '0002_rename_estado_proceso_estado_solicitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='estado_solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitudes_app.estadosolicitud'),
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
