# Generated by Django 4.2.5 on 2024-01-22 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procesos_app', '0003_alter_proceso_estado_solicitud_delete_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
