# Generated by Django 4.2.5 on 2024-01-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos_app', '0004_alter_proceso_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='estado_situacional',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proceso',
            name='organo_universitario_encargado',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proceso',
            name='recomendacion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proceso',
            name='remitido',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
