# Generated by Django 4.2.5 on 2024-02-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos_app', '0005_proceso_estado_situacional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='estado_proceso',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
