# Generated by Django 4.2.5 on 2024-02-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos_app', '0006_alter_proceso_estado_proceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='estado_proceso',
            field=models.BooleanField(default=True),
        ),
    ]
