# Generated by Django 4.2.5 on 2023-09-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoExpediente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
                ('estado', models.BooleanField(default=True)),
                ('fechaCreacion', models.DateTimeField(auto_now=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expedientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idSolicitud', models.IntegerField()),
                ('codigo', models.CharField(max_length=10)),
                ('idEstadoExpediente', models.IntegerField()),
                ('fechaSolicitado', models.DateTimeField(auto_now_add=True)),
                ('fechaRecibido', models.DateTimeField(auto_now=True)),
                ('fechaProceso', models.DateTimeField(auto_now=True)),
                ('fechaTerminado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialExpediente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idExpediente', models.IntegerField()),
                ('titulo', models.TextField()),
                ('descripcion', models.TextField()),
                ('idEstadoExpediente', models.IntegerField()),
                ('idUsuario', models.IntegerField()),
                ('fechaCreacion', models.DateTimeField(auto_now=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
