# Generated by Django 4.2.5 on 2023-09-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idSolicitud', models.IntegerField()),
                ('codigo', models.CharField(max_length=10)),
                ('idEstadoExpediente', models.IntegerField()),
                ('fechaSolicitado', models.DateTimeField()),
                ('fechaRecibido', models.DateTimeField()),
                ('fechaProceso', models.DateTimeField()),
                ('fechaTerminado', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Expedientes',
        ),
        migrations.AlterField(
            model_name='estadoexpediente',
            name='fechaCreacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='estadoexpediente',
            name='fechaModificacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historialexpediente',
            name='fechaCreacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historialexpediente',
            name='fechaModificacion',
            field=models.DateTimeField(),
        ),
    ]
