# Generated by Django 4.2.5 on 2023-09-26 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0002_expediente_delete_expedientes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistorialExpediente',
            new_name='ProcesoExpediente',
        ),
    ]
