# Generated by Django 4.2.5 on 2023-09-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0003_rename_historialexpediente_procesoexpediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesoexpediente',
            name='encargado',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procesoexpediente',
            name='organoUniversitario',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
